### ISSUE TITLE
VoxeetSdk init crash on previous Android version

### ISSUE THREAD

**Issue by Voncoda** [voxeet/android-sdk#3]
**Describe the bug**

Hello! My application is working fine on the last Android simulator (API 29) but I'm getting an issue on simulator API 26 when launching.

**Steps to Reproduce the Problem**

Initialize VoxeetSdk on the onCreate method.

**Minimalistic code (recommended)**

Code:

```java
public class MainActivity extends AppCompatActivity { ...

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        VoxeetSdk.initialize("key", "secret");
}
```

Crash:

```
D/VoxeetHttp: VoxeetHttp: initializing using appId/password
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.classroomonline, PID: 32533
    java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/Retrofit$Builder;
        at com.voxeet.sdk.core.VoxeetHttp.initRetrofit(VoxeetHttp.java:180)
        at com.voxeet.sdk.core.VoxeetHttp.<init>(VoxeetHttp.java:116)
        at com.voxeet.sdk.core.VoxeetHttp.<init>(VoxeetHttp.java:49)
        at com.voxeet.sdk.core.VoxeetHttp$Builder.build(VoxeetHttp.java:412)
        at com.voxeet.sdk.core.VoxeetSdk.<init>(VoxeetSdk.java:180)
        at com.voxeet.sdk.core.VoxeetSdk.initialize(VoxeetSdk.java:91)
        at com.classroomonline.MainActivity.onCreate(MainActivity.java:675)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.Retrofit$Builder" on path: DexPathList[[zip file "/data/app/com.classroomonline-God_eCHQ8ScvYIMPA2H2PA==/base.apk"],nativeLibraryDirectories=[/data/app/com.classroomonline-God_eCHQ8ScvYIMPA2H2PA==/lib/x86, /data/app/com.classroomonline-God_eCHQ8ScvYIMPA2H2PA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.voxeet.sdk.core.VoxeetHttp.initRetrofit(VoxeetHttp.java:180) 
        at com.voxeet.sdk.core.VoxeetHttp.<init>(VoxeetHttp.java:116) 
        at com.voxeet.sdk.core.VoxeetHttp.<init>(VoxeetHttp.java:49) 
        at com.voxeet.sdk.core.VoxeetHttp$Builder.build(VoxeetHttp.java:412) 
        at com.voxeet.sdk.core.VoxeetSdk.<init>(VoxeetSdk.java:180) 
        at com.voxeet.sdk.core.VoxeetSdk.initialize(VoxeetSdk.java:91) 
        at com.classroomonline.MainActivity.onCreate(MainActivity.java:675) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Gradle:

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    defaultConfig {
        applicationId "com.classroomonline"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        android.defaultConfig.vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation("com.voxeet.sdk:public-sdk:${rootProject.ext.voxeetSdkVersion}") {
        transitive = true
    }
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Specifications**

  - Device: Simulator Pixel 2 API 26
  - Platform: Android

**Comment by Voncoda** [comment]
voxeetSdkVersion = "2.0.69.7"

**Comment by codlab** [comment]
The multidex is not enabled. Hence, the class may not be available in the main classes dexed file but in another one after a compilation cycle

**Comment by Voncoda** [comment]
Thank you for your help. Effectively multidex wasn't fully enabled in my project.
Now it's enable but when I start a conference I have a crash (related to "Media"), do you want me to open a new issue and close this one?

**Comment by codlab** [comment]
A new issue should be better 👍
